name: trading_dashboard
description: "NSE Trading Dashboard: A modern, robust, and scalable application for managing stock market data."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 1. Backend & Authentication (Firebase - Your working versions)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  cloud_functions: ^5.0.4
  firebase_messaging: ^15.1.6

  # 2. State Management (Your working versions)
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  visibility_detector: ^0.4.0+2

  # 3. Local Database (Your stable Isar v3)
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

  # 4. UI & Responsive Layout (Your working versions)
  responsive_framework: ^1.5.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # 5. Models & Code Generation (Your working versions)
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # 6. Charts & Data Visualization (Your working versions)
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.40

  # 7. Navigation (Your working version)
  go_router: ^16.0.0

  # 8. Networking & Connectivity (Your working versions)
  connectivity_plus: ^6.0.5
  internet_connection_checker_plus: ^2.5.2

  # 9. Data handling & Export (Your working versions)
  excel: ^4.0.6
  csv: ^6.0.0
  share_plus: ^11.0.0

  # 10. Trading Dashboard Specific
  http: ^1.2.2
  dio: ^5.7.0
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.4
  intl: ^0.19.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generators (Your exact working versions)
  build_runner: ^2.4.7
  freezed: ^2.5.2
  json_serializable: ^6.3.1
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1
  flutter_lints: ^6.0.0
  internet_connection_checker_plus: ^2.5.2
  cloud_functions: ^5.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
